
##  GENERAL DO-FILE COMMENTS
##  Program:		Walk_BB_005.py
##  Project:      	Macroscale Walkability- PhD
##	Sub-Project:	Walkability Index Computation
##  Analyst:		Kern Rocke
##	Date Created:	29/07/2020
##	Date Modified: 	30/07/2020
##  Algorithm Task: Creating Street Intersection Density Layer

# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-07-29 00:22:47
"""
import arcpy

def StreetDensity():  # Street Density in Barbados

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    ED_Boundary_2010 = "\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\ED_Boundary_2010"
    Roads = "\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\RoadPublish1"
    Dissolve_Field_s_ = ["RD_NAME"]
    Attributes_To_Join = "ONLY_FID"
    Output_Type = "POINT"
    Field_s_ = ["Shape"]
    Field_Map_of_Join_Features = "FID_Road_Unsplit \"FID_Road_Unsplit\" true true false 0 Long 0 0,First,#,\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\Road_Unsplit_Intersect,FID_Road_Unsplit,-1,-1;RD_NAME \"RD_NAME\" true true false 80 Text 0 0,First,#,\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\Road_Unsplit,RD_NAME,0,80"
    Search_Radius = "1 Meters"
    Select_2_intersections = "Join_Count >= 3"
    Field_Map_of_Join_Features_ED_Boundary_ = "ENUM_NO1 \"ENUM_NO1\" true true false 4 Long 0 0,First,#,\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\ED_Boundary_2010,ENUM_NO1,-1,-1;PARISHNAM1 \"PARISHNAM1\" true true false 254 Text 0 0,First,#,\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\ED_Boundary_2010,PARISHNAM1,0,254;Join_Count_old \"Join_Count_old\" true true false 0 Long 0 0,First,#,Intersections >/=3,Join_Count,-1,-1;RD_NAME \"RD_NAME\" true true false 80 Text 0 0,First,#,Intersections >/=3,RD_NAME,0,80"
    Geometry_Properties = ["AREA"]
    Area_Unit = "SQUARE_KILOMETERS"
    Field_Name_Existing_or_New_ = "Intersection_Density"
    Expression = "!Join_Count!/!POLY_AREA!"

    # Process: Unsplit Line (Unsplit Line) 
    Unsplit_Road = "\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\Road_Unsplit"
    arcpy.UnsplitLine_management(in_features=Roads, out_feature_class=Unsplit_Road, dissolve_field=Dissolve_Field_s_, statistics_fields=[])

    # Process: Intersect (Intersect) 
    Unsplit_Intersections = "\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\Road_Unsplit_Intersect"
    arcpy.Intersect_analysis(in_features=[[Unsplit_Road, ""]], out_feature_class=Unsplit_Intersections, join_attributes=Attributes_To_Join, cluster_tolerance="", output_type=Output_Type)

    # Process: Delete Identical (Delete Identical) 
    Unique_Intersections = arcpy.DeleteIdentical_management(in_dataset=Unsplit_Intersections, fields=Field_s_, xy_tolerance="", z_tolerance=0)[0]

    # Process: Spatial Join (Spatial Join) 
    Intersections = "\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\Road_Unsplit_Intersect_Spati"
    arcpy.SpatialJoin_analysis(target_features=Unique_Intersections, join_features=Unsplit_Road, out_feature_class=Intersections, join_operation="JOIN_ONE_TO_ONE", join_type="KEEP_ALL", field_mapping=Field_Map_of_Join_Features, match_option="INTERSECT", search_radius=Search_Radius, distance_field_name="")

    # Process: Make Feature Layer (Make Feature Layer) 
    Intersections_2 = "Intersections >/=3"
    arcpy.MakeFeatureLayer_management(in_features=Intersections, out_layer=Intersections_2, where_clause=Select_2_intersections, workspace="", field_info="Join_Count Join_Count VISIBLE NONE;TARGET_FID TARGET_FID VISIBLE NONE;FID_Road_Unsplit FID_Road_Unsplit VISIBLE NONE;RD_NAME RD_NAME VISIBLE NONE")

    # Process: Spatial Join - Intersections to EDs (Spatial Join) 
    Intersection_Density = "\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\ED_Boundary_2010_SpatialJoin"
    arcpy.SpatialJoin_analysis(target_features=ED_Boundary_2010, join_features=Intersections_2, out_feature_class=Intersection_Density, join_operation="JOIN_ONE_TO_ONE", join_type="KEEP_ALL", field_mapping=Field_Map_of_Join_Features_ED_Boundary_, match_option="INTERSECT", search_radius="", distance_field_name="")

    # Process: Add Geometry Attributes (Add Geometry Attributes) 
    Intersection_Density_Geometry = AddGeometryAttributes(Input_Features=Intersection_Density, Geometry_Properties=Geometry_Properties, Length_Unit="", Area_Unit=Area_Unit, Coordinate_System="")[0]

    # Process: Add Field (Add Field) 
    Intersection_Density_Geometry_Den = arcpy.AddField_management(in_table=Intersection_Density_Geometry, field_name="Intersection_Density", field_type="FLOAT", field_precision=None, field_scale=None, field_length=None, field_alias="Intersection Density", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

    # Process: Calculate Field (Calculate Field) 
    Intersection_Density_Final = arcpy.CalculateField_management(in_table=Intersection_Density_Geometry_Den, field=Field_Name_Existing_or_New_, expression=Expression, expression_type="PYTHON3", code_block="", field_type="TEXT")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"\\Mac\Home\Desktop\Walkability\Walkability.gdb", workspace=r"\\Mac\Home\Desktop\Walkability\Walkability.gdb"):
        StreetDensity()
