
##  GENERAL DO-FILE COMMENTS
##  Program:		Walk_BB_001.do
##  Project:      	Macroscale Walkability- PhD
##	Sub-Project:	Walkability Index Computation
##  Analyst:		Kern Rocke
##	Date Created:	28/07/2020
##	Date Modified: 	28/07/2020
##  Algorithm Task: Joining ED and land use layer within GIS


# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-07-28 15:00:02
"""
import arcpy

def LandUseModel():  # Land use mix model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Conversion Tools.tbx")
    Land_Use = "Land_Use_Detail_bb"
    Output_Coordinate_System = "PROJCS['Barbados_1938_Barbados_Grid',GEOGCS['GCS_Barbados_1938',DATUM['D_Barbados_1938',SPHEROID['Clarke_1880_RGS',6378249.145,293.465]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',30000.0],PARAMETER['False_Northing',75000.0],PARAMETER['Central_Meridian',-59.55972222222222],PARAMETER['Scale_Factor',0.9999986],PARAMETER['Latitude_Of_Origin',13.17638888888889],UNIT['Meter',1.0]]"
    Enumeration_Districts = "\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\Residential_Density"
    Join_Operation = "JOIN_ONE_TO_MANY"
    Field_Map_of_Join_Features = "AREA \"AREA\" true true false 20 Double 5 19,First,#,\\\\.psf\\AllFiles\\Volumes\\Secomba\\kernrocke\\Boxcryptor\\DataGroup - repo_data\\data_p145\\version01\\1-input\\GIS Data\\CERMES GIS\\Land_Use_Detail_bb_Project.shp,AREA,-1,-1;LANDUSE \"LANDUSE\" true true false 20 Text 0 0,First,#,\\\\.psf\\AllFiles\\Volumes\\Secomba\\kernrocke\\Boxcryptor\\DataGroup - repo_data\\data_p145\\version01\\1-input\\GIS Data\\CERMES GIS\\Land_Use_Detail_bb_Project.shp,LANDUSE,0,20;LANDUSE_SU \"LANDUSE_SU\" true true false 16 Text 0 0,First,#,\\\\.psf\\AllFiles\\Volumes\\Secomba\\kernrocke\\Boxcryptor\\DataGroup - repo_data\\data_p145\\version01\\1-input\\GIS Data\\CERMES GIS\\Land_Use_Detail_bb_Project.shp,LANDUSE_SU,0,16;ENUM_NO1 \"ENUM_NO1\" true true false 4 Long 0 0,First,#,\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\Residential_Density,ENUM_NO1,-1,-1;PARISHNAM1 \"PARISHNAM1\" true true false 254 Text 0 0,First,#,\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\Residential_Density,PARISHNAM1,0,254;Area_1 \"Area\" true true false 4 Float 0 0,First,#,\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\Residential_Density,Area,-1,-1;Density \"Residential Density\" true true false 4 Float 0 0,First,#,\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\Residential_Density,Density,-1,-1;GlobalID \"GlobalID\" false false true 38 GlobalID 0 0,First,#,\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\Residential_Density,GlobalID,-1,-1"
    Match_Option = "INTERSECT"
    Search_Radius = ""

    # Process: Project (Project) 
    Land_Use_Project = "\\\\.psf\\AllFiles\\Volumes\\Secomba\\kernrocke\\Boxcryptor\\DataGroup - repo_data\\data_p145\\version01\\1-input\\GIS Data\\CERMES GIS\\Land_Use_Detail_bb_Project.shp"
    arcpy.Project_management(in_dataset=Land_Use, out_dataset=Land_Use_Project, out_coor_system=Output_Coordinate_System, transform_method=[], in_coor_system="PROJCS['Barbados_1938_Barbados_Grid',GEOGCS['GCS_Barbados_1938',DATUM['D_Barbados_1938',SPHEROID['Clarke_1880_RGS',6378249.145,293.465]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',30000.0],PARAMETER['False_Northing',75000.0],PARAMETER['Central_Meridian',-59.55972222222222],PARAMETER['Scale_Factor',0.9999986],PARAMETER['Latitude_Of_Origin',13.17638888888889],UNIT['Meter',1.0]]", preserve_shape="NO_PRESERVE_SHAPE", max_deviation="", vertical="NO_VERTICAL")

    # Process: Land Use Repair Geometry (Repair Geometry) 
    Repaired_Land_Use = arcpy.RepairGeometry_management(in_features=Land_Use_Project, delete_null="DELETE_NULL", validation_method="ESRI")[0]

    # Process: ED Boundary Repair Geometry (Repair Geometry) 
    Repaired_ED_Boundary = arcpy.RepairGeometry_management(in_features=Enumeration_Districts, delete_null="DELETE_NULL", validation_method="ESRI")[0]

    # Process: Spatial Join (Spatial Join) 
    ED_Boundary_Land_Use = "\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\Land_Use_Detail_bb_Project_S"
    arcpy.SpatialJoin_analysis(target_features=Repaired_Land_Use, join_features=Repaired_ED_Boundary, out_feature_class=ED_Boundary_Land_Use, join_operation=Join_Operation, join_type="KEEP_ALL", field_mapping=Field_Map_of_Join_Features, match_option=Match_Option, search_radius=Search_Radius, distance_field_name="")

    # Process: Add Field (Add Field) 
    ED_Land_Use_Area = arcpy.AddField_management(in_table=ED_Boundary_Land_Use, field_name="Landuse_area", field_type="FLOAT", field_precision=None, field_scale=None, field_length=None, field_alias="Land Use Area", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

    # Process: Calculate Geometry Attributes (Calculate Geometry Attributes) 
    ED_Land_Use_Geometry = CalculateGeometryAttributes(in_features=ED_Land_Use_Area, geometry_property=[["Landuse_area", "AREA"]], length_unit="", area_unit="SQUARE_KILOMETERS", coordinate_system="", coordinate_format="SAME_AS_INPUT")[0]

    # Process: Table To Excel (Table To Excel) 
    Output_Excel_File_ED_Land_Use = "\\\\Mac\\Home\\Desktop\\Walkability\\Land_Use_Detail_bb_Project_S_TableToExcel.xlsx"
    TableToExcel(Input_Table=ED_Land_Use_Geometry, Output_Excel_File=Output_Excel_File_ED_Land_Use, Use_field_alias_as_column_header="NAME", Use_domain_and_subtype_description="CODE")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"\\Mac\Home\Desktop\Walkability\Walkability.gdb", workspace=r"\\Mac\Home\Desktop\Walkability\Walkability.gdb"):
        LandUseModel()
