
##  GENERAL DO-FILE COMMENTS
##  Program:		Walk_BB_011.py
##  Project:      	Macroscale Walkability- PhD
##	Sub-Project:	Walkability Index Computation
##  Analyst:		Kern Rocke
##	Date Created:	29/07/2020
##	Date Modified: 	30/07/2020
##  Algorithm Task: Walkability Hot Spots Layer

# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-07-30 21:22:02
"""
import arcpy

def HotSpotWalkability():  # Hot Spot Walkability Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    Walk_Index_Layer = "Walk_Index_Layer"

    # Process: Repair Geometry (Repair Geometry) 
    Repaired_Input_Features = arcpy.RepairGeometry_management(in_features=Walk_Index_Layer, delete_null="DELETE_NULL", validation_method="ESRI")[0]

    # Process: Hot Spot Analysis (Getis-Ord Gi*) (Hot Spot Analysis (Getis-Ord Gi*)) 
    Walk_Index_HotSpots = "\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\Walk_Index_HotSpots"
    Results_Field, Probability_Field, Source_ID = arcpy.HotSpots_stats(Input_Feature_Class=Repaired_Input_Features, Input_Field="Walk_index.csv.walkabilty", Output_Feature_Class=Walk_Index_HotSpots, Conceptualization_of_Spatial_Relationships="CONTIGUITY_EDGES_CORNERS", Distance_Method="EUCLIDEAN_DISTANCE", Standardization="ROW", Distance_Band_or_Threshold_Distance=None, Self_Potential_Field="", Weights_Matrix_File="", Apply_False_Discovery_Rate__FDR__Correction="NO_FDR", number_of_neighbors=None)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"\\Mac\Home\Desktop\Walkability\Walkability.gdb", workspace=r"\\Mac\Home\Desktop\Walkability\Walkability.gdb"):
        HotSpotWalkability()
