
##  GENERAL DO-FILE COMMENTS
##  Program:		Walk_BB_010.py
##  Project:      	Macroscale Walkability- PhD
##	Sub-Project:	Walkability Index Computation
##  Analyst:		Kern Rocke
##	Date Created:	30/07/2020
##	Date Modified: 	30/07/2020
##  Algorithm Task: Creating Walkability and SES Layer

# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-07-30 21:21:12
"""
import arcpy

def WalkSES():  # Walkability & SES Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    ED_Boundary_2010 = "\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\ED_Boundary_2010"
    walk_SES_csv = "\\\\Mac\\Home\\Desktop\\walk_SES.csv"

    # Process: Copy Features (Copy Features) 
    Walk_SES = "\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\Walk_SES"
    arcpy.CopyFeatures_management(in_features=ED_Boundary_2010, out_feature_class=Walk_SES, config_keyword="", spatial_grid_1=None, spatial_grid_2=None, spatial_grid_3=None)

    # Process: Add Join (Add Join) 
    Walkability_SES = arcpy.AddJoin_management(in_layer_or_view=Walk_SES, in_field="ENUM_NO1", join_table=walk_SES_csv, join_field="ED", join_type="KEEP_ALL")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"\\Mac\Home\Desktop\Walkability\Walkability.gdb", workspace=r"\\Mac\Home\Desktop\Walkability\Walkability.gdb"):
        WalkSES()
