
##  GENERAL DO-FILE COMMENTS
##  Program:		Walk_BB_004.py
##  Project:      	Macroscale Walkability- PhD
##	Sub-Project:	Walkability Index Computation
##  Analyst:		Kern Rocke
##	Date Created:	28/07/2020
##	Date Modified: 	30/07/2020
##  Algorithm Task: Creating Bus Stop Density Layer

# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-07-28 19:58:06
"""
import arcpy

def BusStopsDensity():  # Bus Stop Density Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    Enumeration_Districts = "\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\ED_Boundary_2010"
    Bus_Stops = "Bus_Stops"

    # Process: Spatial Join (Spatial Join) 
    ED_Bus_Stops = "\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\ED_Boundary_2010_Bus"
    arcpy.SpatialJoin_analysis(target_features=Enumeration_Districts, join_features=Bus_Stops, out_feature_class=ED_Bus_Stops, join_operation="JOIN_ONE_TO_ONE", join_type="KEEP_ALL", field_mapping="ENUM_NO1 \"ENUM_NO1\" true true false 4 Long 0 0,First,#,\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\ED_Boundary_2010,ENUM_NO1,-1,-1;PARISHNAM1 \"PARISHNAM1\" true true false 254 Text 0 0,First,#,\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\ED_Boundary_2010,PARISHNAM1,0,254;POPULATION \"POPULATION\" true true false 4 Long 0 0,First,#,\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\ED_Boundary_2010,POPULATION,-1,-1;Parish \"Parish\" true true false 255 Text 0 0,First,#,Bus_Stops,Parish,0,255", match_option="INTERSECT", search_radius="", distance_field_name="")

    # Process: Add Field (Area) (Add Field) 
    ED_Boundary_2010_Bus = arcpy.AddField_management(in_table=ED_Bus_Stops, field_name="Area", field_type="FLOAT", field_precision=None, field_scale=None, field_length=None, field_alias="Area Square/ km", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

    # Process: Calculate Geometry Attributes (Calculate Geometry Attributes) 
    ED_Boundary_2010_Bus_Area_ = CalculateGeometryAttributes(in_features=ED_Boundary_2010_Bus, geometry_property=[["Area", "AREA"]], length_unit="", area_unit="SQUARE_KILOMETERS", coordinate_system="", coordinate_format="SAME_AS_INPUT")[0]

    # Process: Add Field (Density) (Add Field) 
    ED_Boundary_2010_Bus_Area_Density_ = arcpy.AddField_management(in_table=ED_Boundary_2010_Bus_Area_, field_name="Density", field_type="FLOAT", field_precision=None, field_scale=None, field_length=None, field_alias="Bus Stop Density", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

    # Process: Calculate Field (Calculate Field) 
    Bus_Stop_Density = arcpy.CalculateField_management(in_table=ED_Boundary_2010_Bus_Area_Density_, field="Density", expression="!Join_Count! / !Area!", expression_type="PYTHON3", code_block="", field_type="TEXT")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"\\Mac\Home\Desktop\Walkability\Walkability.gdb", workspace=r"\\Mac\Home\Desktop\Walkability\Walkability.gdb"):
        BusStopsDensity()
