
##  GENERAL DO-FILE COMMENTS
##  Program:		Walk_BB_009.py
##  Project:      	Macroscale Walkability- PhD
##	Sub-Project:	Walkability Index Computation
##  Analyst:		Kern Rocke
##	Date Created:	29/07/2020
##	Date Modified: 	30/07/2020
##  Algorithm Task: Creating Walkability Index Layer

# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-07-29 16:24:53
"""
import arcpy

def Model1():  # Model 1

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    Enumeration_Districts = "\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\ED_Boundary_2010"
    Walk_index_csv = "\\\\Mac\\Home\\Desktop\\Walkability\\Walk_index.csv"

    # Process: Copy Features (Copy Features) 
    Walk_Index = "\\\\Mac\\Home\\Desktop\\Walkability\\Walkability.gdb\\Walk_Index"
    arcpy.CopyFeatures_management(in_features=Enumeration_Districts, out_feature_class=Walk_Index, config_keyword="", spatial_grid_1=None, spatial_grid_2=None, spatial_grid_3=None)

    # Process: Add Join (Add Join) 
    Walkability_Index = arcpy.AddJoin_management(in_layer_or_view=Walk_Index, in_field="ENUM_NO1", join_table=Walk_index_csv, join_field="ED", join_type="KEEP_ALL")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"\\Mac\Home\Desktop\Walkability\Walkability.gdb", workspace=r"\\Mac\Home\Desktop\Walkability\Walkability.gdb"):
        Model1()
